# -*- coding: utf-8 -*-
"""Yolo Pypi - Craft.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RfoEVrIS9lJVKfzTw96HWXbrVrUQhIQl
"""

# pip install yolov5==6.2.3

#from google.colab import drive
#drive.mount('/content/drive')

import yolov5
import cv2
import numpy as np
from PIL import Image as im

def craft(img):
  """Craft: Image of Student Card into the boxes of information needed to extract
  Input: Image of Student card (.jpg, .png, ...)
  Output: The boxes of information (.jpg) """

  # load custom model
  model = yolov5.load('/content/best.pt')
    
  # set model parameters
  model.conf = 0.25  # NMS confidence threshold
  model.iou = 0.45  # NMS IoU threshold
  model.agnostic = False  # NMS class-agnostic
  model.multi_label = False  # NMS multiple labels per box
  model.max_det = 1000  # maximum number of detections per image

  # perform inference
  results = model(img)

  # inference with larger input size
  results = model(img, size=1280)

  # inference with test time augmentation
  results = model(img, augment=True)

  # parse results
  predictions = results.pred[0]
  boxes = predictions[:, :4] # x1, y1, x2, y2
  scores = predictions[:, 4]
  categories = predictions[:, 5]

  # show detection bounding boxes on image
  results.show()

  # crop each box
  crops = results.crop(save=False) 

  # create a dictionary to save all the box and its label
  crops_dict = {}
  for i in range(len(crops)):
    label_and_weight = crops[i]["label"].split()
    label, weight = label_and_weight[0], label_and_weight[1]
    crops_dict.update({label : [weight, crops[i]["im"]]})

  return crops_dict

crafting = craft("/content/the_62_LaMinhQuan.jpg")
